novos botoes
programador-tv/monorepo pull request #100
Opened 2024-08-26 13:02 UTC by kronyer

## Descrição
![image](https://github.com/user-attachments/assets/d17175f4-e520-428b-8b31-30b7fb393179)
Novos botoes na home

## Checklist antes de compartilhar o PR no grupo

- [ ] Escrevi testes que garantem que minha alteração funciona como esperado
- [ ] Executei o comando `dotnet csharpier .` na raiz do projeto
- [ ] Garanti que meu código não gera novos warnings ou alertas do Sonar Cloud
- [ ] Revisei extensivamente a versão final do meu código analisando as alterações que estão entrando e saindo

2024-08-26 21:27 UTC, luizmarcelolm approved these changes

2024-08-31 19:30 UTC, ThesllaDev requested changes
Ótimo trabalho! No entanto, com base nos princípios de Clean Code, sugiro as seguintes alterações:

- Nomeclatura da classe do botão: A nomenclatura atual reflete o novo estilo, mas pode ser mais descritiva. Considere nomes como botao-principal, botao-primario, botao-agendar, ou suas equivalentes em inglês.

- Remoção de estilos não utilizados: Há estilos na classe do botão que não estão sendo utilizados. Veja a imagem abaixo para referência: 
![image](https://github.com/user-attachments/assets/fc231575-5a7f-4701-99cd-15d4737281e2)

2024-09-02 14:03 UTC, ThesllaDev approved these changes
Nice!

2024-09-05 23:57 UTC, eduardoworrel approved these changes

2024-09-05 23:57 UTC, merged