Trocar mãos por setas da página home.
programador-tv/monorepo pull request #43
Opened 2024-08-05 13:58 UTC by LarySampaio

## Descrição

## Checklist antes de compartilhar o PR no grupo

- [ ] Escrevi testes que garantem que minha alteração funciona como esperado
- [ ] Executei o comando `dotnet csharpier .` na raiz do projeto
- [ ] Garanti que meu código não gera novos warnings ou alertas do Sonar Cloud
- [ ] Revisei extensivamente a versão final do meu código analisando as alterações que estão entrando e saindo

2024-08-05 14:09 UTC, kronyer requested changes
Opa! No geral tá ótimo
Não sei se é relacionado com seu pr mas a fonte do card de pedidos de ajuda está herdando da div que ele está inserido:
![image](https://github.com/user-attachments/assets/683048ba-fdfc-4a3b-bb3f-9aecfbf56fe4)

No mais, as setas do pedidos de ajuda parecem não seguir a lógica dos outros, isso é, ser azul quando tiver uma próxima página e cinza quando não, além de que a seta do pedidos de ajuda não está com o border-bottom
![image](https://github.com/user-attachments/assets/0a2f4bdc-bbd0-466c-a72c-12fb624fb400)

2024-08-05 21:55 UTC, kronyer requested changes
Perfeito, uma última coisa, as setinhas do pedidos de ajuda nao ficam azul quando tem uma próxima página disponível
![image](https://github.com/user-attachments/assets/75f51bc9-3ace-4faa-98fa-5737d3ce42df)

2024-08-07 14:49 UTC, kronyer approved these changes

2024-08-07 16:48 UTC, ThesllaDev approved these changes

2024-08-12 00:39 UTC, merged