Permitir postar comentário no timeSelection de tirar dúvidas.
programador-tv/monorepo pull request #46
Opened 2024-08-06 02:44 UTC by leeo-sf

## Descrição

Permitir postar comentário no timeSelection de tirar dúvidas.

Updates no código:
- Nova entidade HelpResponse.
- Novas interfaces e repository's para comunicção do endpoint com o banco.
- Novo endpoint 'HelpResponseEndPoints'.
  - Adicionar novo comentário (POST).
  - Buscar comentário pelo timeSelectionId (GET).
  - Apagar um comentário (GET).
- Modificação no arquivo src/APP.Platform/Pages/Components/ModalJoinTime/_ModalJoinTimeForRequestHelp.cshtml para adicionar div do textarea, div da mensagem após inserir comentário e div dos comentário inseridos.
- Código CSS inserido no arquivo src/APP.Platform/wwwroot/css/codewithme.general.css da linha 1610 até 1703.
- Novas funções no arquivo src/APP.Platform/wwwroot/js/renderComponentsPedirAjuda.js
  - renderRequestedHelpResponse -> monta o textarea caso o usuário não seja o responsável pelo timeSelection e lista as perguntas já cadastradas.
  - sendComment -> Associada ao botão de 'Enviar comentário' insere um novo comentário no timeSelection e chama a função showsCommentMessageSent.
  - deleteHelpResponse -> Associada ao botão '🗑️' deleta um comentário e remove o comentário deletado da tela.
  - showsCommentMessageSent  -> Exibe um alert ao usuário após inserir comentário.
  - qtdEmMinutosCriada -> Descobre o tempo em min, h ou dd do comentário cadastrado para exibir junto com o comentário. Ex. (10min atrás).

Resultado:
![image](https://github.com/user-attachments/assets/c08e10cc-7fcf-4a12-920e-0b69b2d315c7)

## Checklist antes de compartilhar o PR no grupo

- [x] Executei o comando `dotnet csharpier .` na raiz do projeto
- [x] Garanti que meu código não gera novos warnings ou alertas do Sonar Cloud
- [x] Revisei extensivamente a versão final do meu código analisando as alterações que estão entrando e saindo

2024-08-06 14:15 UTC, kronyer requested changes
Você está tendo esse erro ao renderizar o request help ou sou eu?
![image](https://github.com/user-attachments/assets/d1f593d0-d818-42b5-bb7b-9cb692d3744a)

erro -->
<pre><code>System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at AbstractClient.<>c__DisplayClass6_0`1.<<GetAsync>b__0>d.MoveNext() in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 42
--- End of stack trace from previous location ---
   at AbstractClient.CallWithRetry[T](Func`2 func) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 20
   at AbstractClient.CallWithRetry[T](Func`2 func) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 29
   at AbstractClient.GetAsync[T](String route) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 38
   at Infrastructure.WebServices.HelpResponseWebService.GetAll(Guid timeSelectionId) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\Core\HelpResponseWebService.cs:line 31
   at Platform.Services.GetFreeTimeService.PrepareViewModelForRenderRequestedHelpBoard(IEnumerable`1 timeSelectionGroupByPerfilId, ApplicationDbContext _context, IHttpClientFactory httpClientFactory, IPerfilWebService _perfilWebService, IHelpResponseWebService _helpResponseWebService) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\APP.Platform\Services\GetFreeTimeService.cs:line 182
   at APP.Platform.Pages.ScheduleActions.ScheduleActionsModel.OnGetAfterLoadRequestedHelp() in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\APP.Platform\Pages\ScheduleActions\index.cshtml.cs:line 1484
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: */*
Host: localhost:7150
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Cookie: .AspNetCore.Antiforgery.515JfRjNCPU=CfDJ8HS93LRzK7lOmgsdAhlcc_0Vyehgcm69bdba-li1T7tjrOJ31yocN9_H8axJkfOuk3Igigr1hprkXiXnL9EkiD88zBEDCRCuEdSGGTmFAogFaaeNtplkKIwhSKKYRqPkvvzdvBZFlrtmiUBjMUoY4PY; _ga_17S4EYBPS2=GS1.1.1722953132.1.0.1722953136.56.0.0; _ga=GA1.1.1787136283.1722953133; Identity.External=CfDJ8HS93LRzK7lOmgsdAhlcc_1y0exR0eFztoN5_qlgUrgGRyGnVaD1Fc4TKOwmHb5QyQJOIdh8F5MccElg97M3C8wQQa9NuMh942nTSUJhjeicMBKavq2SwfGVUGQ3MCO1QnS26k-bmqXYqE0ojQ6F02TdabRcWHfxsNrlppZfFD7d7UBoPeZb22gy-gDzfEEHAQDFaw0OvLM1zyTKSpOCSryfjfFaWX702OqswTiXAeslBUjVN0X_f_xzreRlkJHqKv_QYZt1UkQdr-4CaiQ6G8GlVHO-tGJ_3KBLZR-510YeSrsu6SxJ6wZsuTu5LR_x0JMyMuED6sWErfI-zpl0ne4ufAE1IEEpTAIhCteKIkGf3jjbFgoWZiWMh15VABfewUd4kBBSx1bJ7tdtAmd-LSkpz79SgahT03po51lmH90bXsQ-JiGm3pWhrlUwGNymRjxwZd2FP0UbYq160r--VmqyCconKpbFfiAEBlkBO0DakxGOsvPILlSnSQVgaij0HwJQUNscgqrbwgL7lth35jgLEqAc_wPkSgNabXGfnzoA-XTMoFy9DpWBSlq0aCHP7uSLY39GCkhONJ3UCpIxGpkMbB-7q_cG9tG8doG8YBFn1U45LNAGk6Buce5Z14V3Nc6jS2qzWBF_n_vuQqIXOduNuxiLg2oov9OHYGriq00A5DaD_9qxEdw-G0y4Y1uinpUEHm4f2fQfV6WnW9kjAgbdx2jNWgJrHXyew3AQYCvpblG_h2TuRSvvlLmQlOoMISOL30k9h1UegUbAs2T1zJbr4sAdyqZTk159cKCMRQVzXDc6pKhyD-Z6tmmGzfk2eeRhPRMT8NVAR5l3QVTOX4jjf2pIiFhPwZRZ0Qml42VQ; .AspNetCore.Identity.Application=CfDJ8HS93LRzK7lOmgsdAhlcc_32LMZx2obGJSxpix-Z5dK-j4cVE_lXVx9_yo8xGEQ9Rv34jfSSqil1AWa5lWEQF-1L-LpVXl6mMDUnybBux5senkCc6CHAdFbqaYvNFTjWf4PGo8KvdWSn9wweEkgGft5bdfY8QVOA4sEl1Q-eh4nZKn-KnpCRvOsxX-HYFOszvNF8YrjVIFwUmNXa262gaOWghXql2BT18SYa1m4UMtfiI9wz8HFuN09EON2oWyWoDz_W4FvZ0I4VlHDI9vcRLwHM7DsOhNmlIA1EW-xX6YhcdVjdZPJHUBycMVt0HUqlf8MEAkvgo2-c2y3yqdU6qBTkvvsn1PpUbH1hRCuc-ELDBhxIKqNFWbiLYA01ItydxraiVW8e4wPkGBmPu83AXBf4yyN9Rg_nhIQw-Pd6VwoYWRJublMYabbKjixo-nvTo8H_41XW89ZhmQrkEQfjhiFG9MIZfgvq-NqosY1JaUj58kVWMY1edMMnVPtfFRtMLpgzW-V3wl-7Y756S1SEb8ZOHNWvHCffMPIkCCgotflsqMJCFFVIA70TC4gtJeheFwmHUJPLAHjHkP0KztZhO152kdUf1UY7Qb8dHq6DmPvhLTasVfL-Vcm12O11o3kEoPF_CRwqjPkDsc6z-Z97EnehNnyeb_tLI20JwAUIyX-5sBKy2ZOjBLxdUhZ38BPlKPuBe3UdobUn9AvT1xQT_lgftw9BwXa6MlalPBsLgpAGogTLB5KgGjNA-S_yNzp4oHAq_V3PwA3T3w6iTYkSw2faemP6BWy_91kflStU5VebPkVDJPhdiOSKnzpCSRZnUXLu5kA6D9_H3j7G2immJ7g
Referer: https://localhost:7150/
TE: trailers
sec-fetch-dest: empty
sec-fetch-mode: cors
sec-fetch-site: same-origin
priority: u=4</code></pre>

2024-08-06 17:26 UTC, leeo-sf commented
> Você está tendo esse erro ao renderizar o request help ou sou eu? ![image](https://private-user-images.githubusercontent.com/152650887/355483339-d1f593d0-d818-42b5-bb7b-9cb692d3744a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjUwMTMsIm5iZiI6MTcyMjk2NDcxMywicGF0aCI6Ii8xNTI2NTA4ODcvMzU1NDgzMzM5LWQxZjU5M2QwLWQ4MTgtNDJiNS1iYjdiLTljYjY5MmQzNzQ0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNzE4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzZkN2EzZjVlZTEwNGVkNzlmMDQzZThkZWZiNDdhMzc4M2MxZmU3NmYzOTBhOTI2MTEzYzcwMjg3ZDQyNDM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.motPfBxwU1AK2oeat2Zquk7-_gOxJ1QWlUMhpaFw3Vw)
> 
> erro -->
> 
> ```
> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).
>    at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
>    at AbstractClient.<>c__DisplayClass6_0`1.<b__0>d.MoveNext() in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 42
> --- End of stack trace from previous location ---
>    at AbstractClient.CallWithRetry[T](Func`2 func) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 20
>    at AbstractClient.CallWithRetry[T](Func`2 func) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 29
>    at AbstractClient.GetAsync[T](String route) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\abstract\AbstractClient.cs:line 38
>    at Infrastructure.WebServices.HelpResponseWebService.GetAll(Guid timeSelectionId) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\Core\Infrastructure\WebServices\Core\HelpResponseWebService.cs:line 31
>    at Platform.Services.GetFreeTimeService.PrepareViewModelForRenderRequestedHelpBoard(IEnumerable`1 timeSelectionGroupByPerfilId, ApplicationDbContext _context, IHttpClientFactory httpClientFactory, IPerfilWebService _perfilWebService, IHelpResponseWebService _helpResponseWebService) in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\APP.Platform\Services\GetFreeTimeService.cs:line 182
>    at APP.Platform.Pages.ScheduleActions.ScheduleActionsModel.OnGetAfterLoadRequestedHelp() in C:\Users\pedro\OneDrive\Área de Trabalho\ProgramadorTVPublic\monorepo\src\APP.Platform\Pages\ScheduleActions\index.cshtml.cs:line 1484
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
>    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
>    at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
> 
> HEADERS
> =======
> Accept: */*
> Host: localhost:7150
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:128.0) Gecko/20100101 Firefox/128.0
> Accept-Encoding: gzip, deflate, br, zstd
> Accept-Language: en-US,en;q=0.5
> Cookie: .AspNetCore.Antiforgery.515JfRjNCPU=CfDJ8HS93LRzK7lOmgsdAhlcc_0Vyehgcm69bdba-li1T7tjrOJ31yocN9_H8axJkfOuk3Igigr1hprkXiXnL9EkiD88zBEDCRCuEdSGGTmFAogFaaeNtplkKIwhSKKYRqPkvvzdvBZFlrtmiUBjMUoY4PY; _ga_17S4EYBPS2=GS1.1.1722953132.1.0.1722953136.56.0.0; _ga=GA1.1.1787136283.1722953133; Identity.External=CfDJ8HS93LRzK7lOmgsdAhlcc_1y0exR0eFztoN5_qlgUrgGRyGnVaD1Fc4TKOwmHb5QyQJOIdh8F5MccElg97M3C8wQQa9NuMh942nTSUJhjeicMBKavq2SwfGVUGQ3MCO1QnS26k-bmqXYqE0ojQ6F02TdabRcWHfxsNrlppZfFD7d7UBoPeZb22gy-gDzfEEHAQDFaw0OvLM1zyTKSpOCSryfjfFaWX702OqswTiXAeslBUjVN0X_f_xzreRlkJHqKv_QYZt1UkQdr-4CaiQ6G8GlVHO-tGJ_3KBLZR-510YeSrsu6SxJ6wZsuTu5LR_x0JMyMuED6sWErfI-zpl0ne4ufAE1IEEpTAIhCteKIkGf3jjbFgoWZiWMh15VABfewUd4kBBSx1bJ7tdtAmd-LSkpz79SgahT03po51lmH90bXsQ-JiGm3pWhrlUwGNymRjxwZd2FP0UbYq160r--VmqyCconKpbFfiAEBlkBO0DakxGOsvPILlSnSQVgaij0HwJQUNscgqrbwgL7lth35jgLEqAc_wPkSgNabXGfnzoA-XTMoFy9DpWBSlq0aCHP7uSLY39GCkhONJ3UCpIxGpkMbB-7q_cG9tG8doG8YBFn1U45LNAGk6Buce5Z14V3Nc6jS2qzWBF_n_vuQqIXOduNuxiLg2oov9OHYGriq00A5DaD_9qxEdw-G0y4Y1uinpUEHm4f2fQfV6WnW9kjAgbdx2jNWgJrHXyew3AQYCvpblG_h2TuRSvvlLmQlOoMISOL30k9h1UegUbAs2T1zJbr4sAdyqZTk159cKCMRQVzXDc6pKhyD-Z6tmmGzfk2eeRhPRMT8NVAR5l3QVTOX4jjf2pIiFhPwZRZ0Qml42VQ; .AspNetCore.Identity.Application=CfDJ8HS93LRzK7lOmgsdAhlcc_32LMZx2obGJSxpix-Z5dK-j4cVE_lXVx9_yo8xGEQ9Rv34jfSSqil1AWa5lWEQF-1L-LpVXl6mMDUnybBux5senkCc6CHAdFbqaYvNFTjWf4PGo8KvdWSn9wweEkgGft5bdfY8QVOA4sEl1Q-eh4nZKn-KnpCRvOsxX-HYFOszvNF8YrjVIFwUmNXa262gaOWghXql2BT18SYa1m4UMtfiI9wz8HFuN09EON2oWyWoDz_W4FvZ0I4VlHDI9vcRLwHM7DsOhNmlIA1EW-xX6YhcdVjdZPJHUBycMVt0HUqlf8MEAkvgo2-c2y3yqdU6qBTkvvsn1PpUbH1hRCuc-ELDBhxIKqNFWbiLYA01ItydxraiVW8e4wPkGBmPu83AXBf4yyN9Rg_nhIQw-Pd6VwoYWRJublMYabbKjixo-nvTo8H_41XW89ZhmQrkEQfjhiFG9MIZfgvq-NqosY1JaUj58kVWMY1edMMnVPtfFRtMLpgzW-V3wl-7Y756S1SEb8ZOHNWvHCffMPIkCCgotflsqMJCFFVIA70TC4gtJeheFwmHUJPLAHjHkP0KztZhO152kdUf1UY7Qb8dHq6DmPvhLTasVfL-Vcm12O11o3kEoPF_CRwqjPkDsc6z-Z97EnehNnyeb_tLI20JwAUIyX-5sBKy2ZOjBLxdUhZ38BPlKPuBe3UdobUn9AvT1xQT_lgftw9BwXa6MlalPBsLgpAGogTLB5KgGjNA-S_yNzp4oHAq_V3PwA3T3w6iTYkSw2faemP6BWy_91kflStU5VebPkVDJPhdiOSKnzpCSRZnUXLu5kA6D9_H3j7G2immJ7g
> Referer: https://localhost:7150/
> TE: trailers
> sec-fetch-dest: empty
> sec-fetch-mode: cors
> sec-fetch-site: same-origin
> priority: u=4
> ```

Tentei reproduzir o erro mas não consegui. 
![image](https://github.com/user-attachments/assets/b1752038-9123-454b-8e7f-6e8b2b26934c)

2024-08-06 22:25 UTC, kronyer approved these changes
Top maninho!

2024-08-06 22:29 UTC, leeo-sf commented
Valeuuu men!

2024-08-20 15:22 UTC, eduardoworrel approved these changes

2024-08-20 15:26 UTC, merged