Ma feature omite videos privados
programador-tv/monorepo pull request #64
Opened 2024-08-13 00:04 UTC by oimarcella

## Descrição
Adiciona um checkbox na seção de vídeos de um canal, para permitir exibir ou não os vídeos privados para o dono do próprio canal.

## Checklist antes de compartilhar o PR no grupo

- [ ] Escrevi testes que garantem que minha alteração funciona como esperado
- [x] Executei o comando `dotnet csharpier .` na raiz do projeto
- [x] Garanti que meu código não gera novos warnings ou alertas do Sonar Cloud
- [x] Revisei extensivamente a versão final do meu código analisando as alterações que estão entrando e saindo

2024-08-13 00:14 UTC, eduardoworrel commented on src/APP.Platform/Pages/Canal/Index.cshtml.cs
> +        var countTotal = _context.Lives.Count(e =>
Acredito que o count não pe mais usado no front

2024-08-13 00:15 UTC, eduardoworrel commented on src/APP.Platform/Services/LiveService.cs
> +        if (perfilLogInId == perfilOwner.Id && perfilOwner.Id == perfilLogInId)
mesma condição duplicada

2024-08-13 14:06 UTC, kronyer requested changes
Bom dia, acho que sua mudança ta fazendo a div das setinhas na pagina do canal nao renderizar (na foto está correto, é so uma foto para se localizar):
![image](https://github.com/user-attachments/assets/90d4f741-7d47-4d6b-a591-45d0318c0415)

É relativo ao fechamento correto das divs no Index.cshtml
Também nao sei se foi você que escreveu, mas a boa prática é escrever <div> ou qualquer outra tag sem o espaçamento, <div>, não < div >.

Sobre sua task, parece estar funcionando corretamente, mas nao consegui entender onde eu poderia deixar o vídeo privado

2024-08-14 14:29 UTC, oimarcella commented
Olá

- Sobre as setas, não entendo o porquê possa ter sido afetado, visto que essa parte está num arquivo que não foi alterado nessa branch.
Antes de commitar minhas primeiras alterações eu fiz um fetch e pull da main e mergeei com a minha pois eu já estava muito atrás.
![image](https://github.com/user-attachments/assets/d7fba892-e303-4a9c-bc2d-8cb8df9f219e)

- Sobre onde poderia deixar o vídeo privado, seria na tela para editar as informações do vídeo mesmo:
![image](https://github.com/user-attachments/assets/ab2760be-34fb-46de-9cd6-02301e3a5b07)

![image](https://github.com/user-attachments/assets/6e616f0c-1d52-40d7-b77b-15cfbafda756)

2024-08-14 15:37 UTC, oimarcella commented
> É relativo ao fechamento correto das divs no Index.cshtml Também nao sei se foi você que escreveu, mas a boa prática é escrever <div> ou qualquer outra tag sem o espaçamento, <div>, não < div >.


Tinha razão, branch atualizada com novo commit!
Obg

2024-08-15 10:29 UTC, eduardoworrel approved these changes

2024-08-15 10:30 UTC, merged